const homeRoutes = require("./home.route");
const admissionsRoutes = require("./admissions.route");
const academicRoute = require("./academic.route");
const placementRoute = require("./placement.route");
const campusRoutes = require("./campus.route");
const about = require("./about.route");
const AdvertisemenRoutes = require("./advertisement.route");
const newsRoutes = require("./news.route");
const adminRoutes = require("./adminRoutes");
module.exports = function setRoutes(app) {
  homeRoutes(app);
  admissionsRoutes(app);
  academicRoute(app);
  placementRoute(app);
  campusRoutes(app);
  AdvertisemenRoutes(app);
  about(app);
  newsRoutes(app);
  adminRoutes(app);
};
